import React, { useEffect, useState } from 'react';
import { commercialService, CommercialSettings, HouseholdInvite, HouseholdMember, MemberRole } from '../services/commercialService';
import { Button } from './ui/Button';
import { Building2, CreditCard, Palette, ShieldCheck, Upload, Users, X } from 'lucide-react';

export const CommercialSettingsModal: React.FC<{ open: boolean; onClose: () => void; onBrandUpdated: () => void }> = ({ open, onClose, onBrandUpdated }) => {
  const [tab, setTab] = useState<'client'|'users'|'brand'|'plan'>('client');
  const [settings, setSettings] = useState<CommercialSettings | null>(null);
  const [members, setMembers] = useState<HouseholdMember[]>([]); const [invites, setInvites] = useState<HouseholdInvite[]>([]);
  const [email, setEmail] = useState(''); const [role, setRole] = useState<MemberRole>('member'); const [message, setMessage] = useState('');
  const canManage = settings?.role === 'owner' || settings?.role === 'admin';
  const load = async () => { const current = await commercialService.getSettings(); setSettings(current); if (canManage || current.role === 'owner' || current.role === 'admin') { const data = await commercialService.getMembers(current.id); setMembers(data.members); setInvites(data.invites); } };
  useEffect(() => { if (open) load().catch(e => setMessage(e.message)); }, [open]);
  if (!open || !settings) return null;
  const save = async () => { setMessage(''); try { await commercialService.updateSettings(settings); setMessage('Configurações atualizadas.'); onBrandUpdated(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao salvar.'); } };
  const tabs = [{id:'client',label:'Cliente',icon:Building2},{id:'users',label:'Usuários',icon:Users},{id:'brand',label:'Identidade',icon:Palette},{id:'plan',label:'Plano',icon:CreditCard}] as const;
  return <div className="fixed inset-0 z-50 bg-slate-950/60 p-4 overflow-y-auto"><div className="max-w-5xl mx-auto bg-white rounded-2xl shadow-2xl overflow-hidden">
    <header className="p-5 border-b flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-600">Configurações do cliente</p><h2 className="text-2xl font-bold">{settings.name}</h2></div><button onClick={onClose}><X /></button></header>
    <div className="grid md:grid-cols-[210px_1fr] min-h-[520px]"><nav className="bg-slate-50 border-r p-3">{tabs.map(item => <button key={item.id} onClick={() => setTab(item.id)} className={`w-full flex items-center gap-2 px-3 py-3 rounded-lg text-sm font-semibold ${tab===item.id?'bg-emerald-600 text-white':'text-slate-600 hover:bg-white'}`}><item.icon className="w-4 h-4"/>{item.label}</button>)}</nav>
      <main className="p-6">
        {tab==='client' && <div className="space-y-5"><h3 className="font-bold text-lg">Dados do espaço familiar</h3><label className="block text-sm font-semibold">Nome da família ou cliente<input disabled={!canManage} className="mt-1 w-full border rounded-lg p-3 font-normal" value={settings.name} onChange={e=>setSettings({...settings,name:e.target.value})}/></label><div className="rounded-xl bg-slate-50 border p-4 flex gap-3"><ShieldCheck className="text-emerald-600"/><div><strong>Dados isolados</strong><p className="text-sm text-slate-500">Receitas, despesas e orçamento pertencem exclusivamente a este cliente.</p></div></div>{canManage && <Button onClick={save}>Salvar dados</Button>}</div>}
        {tab==='users' && <div className="space-y-5"><div><h3 className="font-bold text-lg">Usuários e acessos</h3><p className="text-sm text-slate-500">{members.filter(m=>m.active).length} de {settings.licensedUsers} licenças utilizadas.</p></div><div className="space-y-2">{members.map(member=><div key={member.user_id} className="border rounded-xl p-3 flex items-center justify-between gap-3"><div><strong>{member.display_name}</strong><p className="text-xs text-slate-500">{member.active?'Ativo':'Suspenso'}</p></div><div className="flex gap-2"><select disabled={!canManage || member.role==='owner'} value={member.role} onChange={async e=>{await commercialService.updateMember(settings.id,member.user_id,{role:e.target.value as MemberRole}); await load();}} className="border rounded-lg p-2 text-sm"><option value="owner">Proprietário</option><option value="admin">Administrador</option><option value="member">Membro</option><option value="viewer">Somente leitura</option></select>{canManage&&member.role!=='owner'&&<button onClick={async()=>{await commercialService.updateMember(settings.id,member.user_id,{active:!member.active});await load();}} className="text-xs font-bold text-rose-600">{member.active?'Suspender':'Reativar'}</button>}</div></div>)}</div>{canManage&&<form onSubmit={async e=>{e.preventDefault();try{await commercialService.invite(settings.id,email,role);setEmail('');setMessage('Convite criado.');await load();}catch(err){setMessage(err instanceof Error?err.message:'Falha no convite.');}}} className="grid md:grid-cols-[1fr_170px_auto] gap-2"><input required type="email" placeholder="email@exemplo.com" className="border rounded-lg p-3" value={email} onChange={e=>setEmail(e.target.value)}/><select className="border rounded-lg p-3" value={role} onChange={e=>setRole(e.target.value as MemberRole)}><option value="admin">Administrador</option><option value="member">Membro</option><option value="viewer">Somente leitura</option></select><Button>Convidar</Button></form>}<div className="space-y-1">{invites.filter(i=>i.status==='pending').map(i=><p key={i.id} className="text-sm text-slate-500">Convite pendente: {i.email} ({i.role})</p>)}</div></div>}
        {tab==='brand' && <div className="space-y-5"><h3 className="font-bold text-lg">Identidade visual</h3><div className="border rounded-xl p-4 flex items-center gap-4">{settings.branding.logoUrl?<img src={settings.branding.logoUrl} className="w-20 h-20 object-contain rounded-xl"/>:<div className="w-20 h-20 bg-slate-100 rounded-xl flex items-center justify-center"><Palette/></div>}<label className="cursor-pointer text-sm font-bold text-emerald-700"><Upload className="inline w-4 h-4 mr-1"/>Enviar logo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" disabled={!canManage} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const url=await commercialService.uploadLogo(settings.id,file);setSettings({...settings,branding:{...settings.branding,logoUrl:url}});}}/></label></div><label className="block text-sm font-semibold">Nome exibido<input disabled={!canManage} className="mt-1 w-full border rounded-lg p-3" value={settings.branding.displayName} onChange={e=>setSettings({...settings,branding:{...settings.branding,displayName:e.target.value}})}/></label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-semibold">Cor principal<input disabled={!canManage} type="color" className="mt-1 w-full h-12" value={settings.branding.primaryColor} onChange={e=>setSettings({...settings,branding:{...settings.branding,primaryColor:e.target.value}})}/></label><label className="text-sm font-semibold">Cor de destaque<input disabled={!canManage} type="color" className="mt-1 w-full h-12" value={settings.branding.accentColor} onChange={e=>setSettings({...settings,branding:{...settings.branding,accentColor:e.target.value}})}/></label></div>{canManage&&<Button onClick={save}>Aplicar identidade</Button>}</div>}
        {tab==='plan' && <div className="space-y-5"><h3 className="font-bold text-lg">Plano e assinatura</h3><div className="grid sm:grid-cols-3 gap-3"><div className="border rounded-xl p-4"><span className="text-xs text-slate-500">PLANO</span><strong className="block text-xl capitalize">{settings.plan}</strong></div><div className="border rounded-xl p-4"><span className="text-xs text-slate-500">STATUS</span><strong className="block text-xl capitalize">{settings.status}</strong></div><div className="border rounded-xl p-4"><span className="text-xs text-slate-500">USUÁRIOS</span><strong className="block text-xl">{settings.licensedUsers}</strong></div></div><p className="text-sm text-slate-500">A contratação e alteração do plano serão vinculadas ao meio de pagamento na próxima etapa comercial.</p></div>}
        {message&&<p className="mt-5 p-3 rounded-lg bg-emerald-50 text-emerald-800 text-sm">{message}</p>}
      </main></div></div></div>;
};
